"""add_category_to_discussions

Revision ID: 1670cfccff2e
Revises: ada4a00f04d2
Create Date: 2026-08-23 19:00:23.343666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1670cfccff2e'
down_revision: Union[str, Sequence[str], None] = 'ada4a00f04d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussions', sa.Column('category', sa.String(length=64), server_default='General', nullable=False))
    op.create_index(op.f('ix_discussions_category'), 'discussions', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_discussions_category'), table_name='discussions')
    op.drop_column('discussions', 'category')
    # ### end Alembic commands ###
