"""Baseline schema

Revision ID: 1c77ea59469c
Revises: 
Create Date: 2026-08-14 11:44:32.536281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c77ea59469c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actors_owner_id'), 'actors', ['owner_id'], unique=False)
    op.create_index(op.f('ix_actors_type'), 'actors', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=39), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_repositories_slug'), 'repositories', ['slug'], unique=False)
    op.create_table('changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('base_commit', sa.String(length=64), nullable=True),
    sa.Column('resulting_commit', sa.String(length=64), nullable=True),
    sa.Column('operation_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('proposed', 'recorded', 'blocked', 'rejected')", name='ck_changes_status'),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_key', name='uq_changes_operation_key')
    )
    op.create_index(op.f('ix_changes_actor_id'), 'changes', ['actor_id'], unique=False)
    op.create_index(op.f('ix_changes_operation_key'), 'changes', ['operation_key'], unique=False)
    op.create_index(op.f('ix_changes_repository_id'), 'changes', ['repository_id'], unique=False)
    op.create_index(op.f('ix_changes_status'), 'changes', ['status'], unique=False)
    op.create_table('git_push_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('before_refs_json', sa.Text(), nullable=False),
    sa.Column('after_refs_json', sa.Text(), nullable=False),
    sa.Column('integrity_version', sa.Integer(), nullable=False),
    sa.Column('integrity_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("\n        (\n            status = 'processed'\n            AND processed_at IS NOT NULL\n        )\n        OR\n        (\n            status != 'processed'\n            AND processed_at IS NULL\n        )\n        ", name='ck_git_push_events_processed_at_consistency'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'processed', 'failed', 'dead_letter')", name='ck_git_push_events_status'),
    sa.CheckConstraint('attempts >= 0', name='ck_git_push_events_attempts_nonnegative'),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_git_push_events_actor_id'), 'git_push_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_git_push_events_integrity_hash'), 'git_push_events', ['integrity_hash'], unique=False)
    op.create_index(op.f('ix_git_push_events_lease_expires_at'), 'git_push_events', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_git_push_events_next_attempt_at'), 'git_push_events', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_git_push_events_repository_id'), 'git_push_events', ['repository_id'], unique=False)
    op.create_index(op.f('ix_git_push_events_status'), 'git_push_events', ['status'], unique=False)
    op.create_index(op.f('ix_git_push_events_worker_id'), 'git_push_events', ['worker_id'], unique=False)
    op.create_table('change_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_change_id', sa.String(length=36), nullable=False),
    sa.Column('target_change_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_change_id'], ['changes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_change_id'], ['changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_dependencies_source_change_id'), 'change_dependencies', ['source_change_id'], unique=False)
    op.create_index(op.f('ix_change_dependencies_target_change_id'), 'change_dependencies', ['target_change_id'], unique=False)
    op.create_table('change_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_events_actor_id'), 'change_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_change_events_change_id'), 'change_events', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_events_event_type'), 'change_events', ['event_type'], unique=False)
    op.create_table('change_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('old_hash', sa.String(length=64), nullable=True),
    sa.Column('new_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_files_change_id'), 'change_files', ['change_id'], unique=False)
    op.create_table('change_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_reviews_change_id'), 'change_reviews', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_reviews_requested_by'), 'change_reviews', ['requested_by'], unique=False)
    op.create_index(op.f('ix_change_reviews_reviewer_id'), 'change_reviews', ['reviewer_id'], unique=False)
    op.create_index(op.f('ix_change_reviews_status'), 'change_reviews', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_change_reviews_status'), table_name='change_reviews')
    op.drop_index(op.f('ix_change_reviews_reviewer_id'), table_name='change_reviews')
    op.drop_index(op.f('ix_change_reviews_requested_by'), table_name='change_reviews')
    op.drop_index(op.f('ix_change_reviews_change_id'), table_name='change_reviews')
    op.drop_table('change_reviews')
    op.drop_index(op.f('ix_change_files_change_id'), table_name='change_files')
    op.drop_table('change_files')
    op.drop_index(op.f('ix_change_events_event_type'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_change_id'), table_name='change_events')
    op.drop_index(op.f('ix_change_events_actor_id'), table_name='change_events')
    op.drop_table('change_events')
    op.drop_index(op.f('ix_change_dependencies_target_change_id'), table_name='change_dependencies')
    op.drop_index(op.f('ix_change_dependencies_source_change_id'), table_name='change_dependencies')
    op.drop_table('change_dependencies')
    op.drop_index(op.f('ix_git_push_events_worker_id'), table_name='git_push_events')
    op.drop_index(op.f('ix_git_push_events_status'), table_name='git_push_events')
    op.drop_index(op.f('ix_git_push_events_repository_id'), table_name='git_push_events')
    op.drop_index(op.f('ix_git_push_events_next_attempt_at'), table_name='git_push_events')
    op.drop_index(op.f('ix_git_push_events_lease_expires_at'), table_name='git_push_events')
    op.drop_index(op.f('ix_git_push_events_integrity_hash'), table_name='git_push_events')
    op.drop_index(op.f('ix_git_push_events_actor_id'), table_name='git_push_events')
    op.drop_table('git_push_events')
    op.drop_index(op.f('ix_changes_status'), table_name='changes')
    op.drop_index(op.f('ix_changes_repository_id'), table_name='changes')
    op.drop_index(op.f('ix_changes_operation_key'), table_name='changes')
    op.drop_index(op.f('ix_changes_actor_id'), table_name='changes')
    op.drop_table('changes')
    op.drop_index(op.f('ix_repositories_slug'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_actors_type'), table_name='actors')
    op.drop_index(op.f('ix_actors_owner_id'), table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
