"""add github issue provenance

Revision ID: 79c24d6dd026
Revises: a9b8c7d6e5f4
Create Date: 2026-09-03 01:44:08.407972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79c24d6dd026'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('governance_policies')
    op.alter_column('agent_repository_access', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('agent_repository_access', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_agent_repository_access_agent_id'), 'agent_repository_access', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_repository_access_repository_id'), 'agent_repository_access', ['repository_id'], unique=False)
    op.add_column('issue_comments', sa.Column('github_comment_id', sa.String(length=64), nullable=True))
    op.add_column('issue_comments', sa.Column('github_html_url', sa.Text(), nullable=True))
    op.add_column('issue_comments', sa.Column('github_author_login', sa.String(length=255), nullable=True))
    op.alter_column('issue_comments', 'author_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_issue_comments_github_comment_id'), 'issue_comments', ['github_comment_id'], unique=False)
    op.drop_constraint(op.f('issue_comments_author_id_fkey'), 'issue_comments', type_='foreignkey')
    op.create_foreign_key(None, 'issue_comments', 'actors', ['author_id'], ['id'], ondelete='SET NULL')
    op.add_column('issues', sa.Column('github_issue_id', sa.String(length=64), nullable=True))
    op.add_column('issues', sa.Column('github_issue_number', sa.Integer(), nullable=True))
    op.add_column('issues', sa.Column('github_html_url', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('source_type', sa.String(length=32), nullable=False))
    op.add_column('issues', sa.Column('agent_id', sa.String(length=36), nullable=True))
    op.add_column('issues', sa.Column('agent_session_id', sa.String(length=36), nullable=True))
    op.add_column('issues', sa.Column('task_id', sa.String(length=36), nullable=True))
    op.add_column('issues', sa.Column('actor_id', sa.String(length=36), nullable=True))
    op.add_column('issues', sa.Column('github_author_login', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_issues_author_id'), table_name='issues')
    op.create_index(op.f('ix_issues_actor_id'), 'issues', ['actor_id'], unique=False)
    op.create_index(op.f('ix_issues_agent_id'), 'issues', ['agent_id'], unique=False)
    op.create_index(op.f('ix_issues_agent_session_id'), 'issues', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_issues_github_issue_id'), 'issues', ['github_issue_id'], unique=False)
    op.create_index(op.f('ix_issues_github_issue_number'), 'issues', ['github_issue_number'], unique=False)
    op.create_index(op.f('ix_issues_source_type'), 'issues', ['source_type'], unique=False)
    op.create_index(op.f('ix_issues_task_id'), 'issues', ['task_id'], unique=False)
    op.create_unique_constraint('uq_issue_repository_github_number', 'issues', ['repository_id', 'github_issue_number'])
    op.drop_constraint(op.f('issues_author_id_fkey'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'actors', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_column('issues', 'author_id')
    op.drop_index(op.f('uq_repo_provider_external'), table_name='repositories', postgresql_where='(external_id IS NOT NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_repo_provider_external'), 'repositories', ['provider_type', 'external_id'], unique=True, postgresql_where='(external_id IS NOT NULL)')
    op.add_column('issues', sa.Column('author_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_author_id_fkey'), 'issues', 'actors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_issue_repository_github_number', 'issues', type_='unique')
    op.drop_index(op.f('ix_issues_task_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_source_type'), table_name='issues')
    op.drop_index(op.f('ix_issues_github_issue_number'), table_name='issues')
    op.drop_index(op.f('ix_issues_github_issue_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_agent_session_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_agent_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_actor_id'), table_name='issues')
    op.create_index(op.f('ix_issues_author_id'), 'issues', ['author_id'], unique=False)
    op.drop_column('issues', 'github_author_login')
    op.drop_column('issues', 'actor_id')
    op.drop_column('issues', 'task_id')
    op.drop_column('issues', 'agent_session_id')
    op.drop_column('issues', 'agent_id')
    op.drop_column('issues', 'source_type')
    op.drop_column('issues', 'github_html_url')
    op.drop_column('issues', 'github_issue_number')
    op.drop_column('issues', 'github_issue_id')
    op.drop_constraint(None, 'issue_comments', type_='foreignkey')
    op.create_foreign_key(op.f('issue_comments_author_id_fkey'), 'issue_comments', 'actors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_issue_comments_github_comment_id'), table_name='issue_comments')
    op.alter_column('issue_comments', 'author_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('issue_comments', 'github_author_login')
    op.drop_column('issue_comments', 'github_html_url')
    op.drop_column('issue_comments', 'github_comment_id')
    op.drop_index(op.f('ix_agent_repository_access_repository_id'), table_name='agent_repository_access')
    op.drop_index(op.f('ix_agent_repository_access_agent_id'), table_name='agent_repository_access')
    op.alter_column('agent_repository_access', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('agent_repository_access', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_table('governance_policies',
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enforce_branch_protection', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('minimum_pr_approvals', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('restrict_public_repositories', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('require_signed_commits', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('governance_policies_organization_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('governance_policies_pkey'))
    )
    # ### end Alembic commands ###
