"""add_issues_discussions_agent_messages

Revision ID: 7ebd1d922b83
Revises: b612f0b58610
Create Date: 2026-08-21 10:33:06.404224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebd1d922b83'
down_revision: Union[str, Sequence[str], None] = 'b612f0b58610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_agent_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_agent_id', sa.String(length=36), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_messages_receiver_agent_id'), 'agent_messages', ['receiver_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_sender_agent_id'), 'agent_messages', ['sender_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_topic_id'), 'agent_messages', ['topic_id'], unique=False)
    op.create_table('discussions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_author_id'), 'discussions', ['author_id'], unique=False)
    op.create_index(op.f('ix_discussions_repository_id'), 'discussions', ['repository_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('repository_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_author_id'), 'issues', ['author_id'], unique=False)
    op.create_index(op.f('ix_issues_repository_id'), 'issues', ['repository_id'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_table('discussion_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('discussion_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_comments_author_id'), 'discussion_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_discussion_comments_discussion_id'), 'discussion_comments', ['discussion_id'], unique=False)
    op.create_table('issue_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('issue_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_comments_author_id'), 'issue_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_issue_comments_issue_id'), 'issue_comments', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_comments_issue_id'), table_name='issue_comments')
    op.drop_index(op.f('ix_issue_comments_author_id'), table_name='issue_comments')
    op.drop_table('issue_comments')
    op.drop_index(op.f('ix_discussion_comments_discussion_id'), table_name='discussion_comments')
    op.drop_index(op.f('ix_discussion_comments_author_id'), table_name='discussion_comments')
    op.drop_table('discussion_comments')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_repository_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_author_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_discussions_repository_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_author_id'), table_name='discussions')
    op.drop_table('discussions')
    op.drop_index(op.f('ix_agent_messages_topic_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_sender_agent_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_receiver_agent_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    # ### end Alembic commands ###
