"""Add priority_index to tasks

Revision ID: 86b09d8b5bc4
Revises: fb26a66adb76
Create Date: 2026-08-23 17:07:56.833462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b09d8b5bc4'
down_revision: Union[str, Sequence[str], None] = 'fb26a66adb76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority_index', sa.Float(), nullable=False, server_default='0.0'))
    op.create_index(op.f('ix_tasks_priority_index'), 'tasks', ['priority_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_priority_index'), table_name='tasks')
    op.drop_column('tasks', 'priority_index')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###
