from datetime import datetime, timezone
from statistics import median

from fastapi import APIRouter, Depends
from pydantic import BaseModel, ConfigDict
from sqlalchemy import func, or_, select
from sqlalchemy.orm import Session

from app.api.dependencies import get_current_user
from app.db.session import get_db
from app.models.actor import Actor
from app.models.agent import Agent
from app.models.agent_session import AgentSession
from app.models.change import Change
from app.models.ci_job import CIJob
from app.models.deployment import Deployment
from app.models.environment import Environment
from app.models.inline_review_comment import InlineReviewComment
from app.models.pull_request import PullRequest
from app.models.repository import Repository
from app.models.task import Task
from app.models.user import User

router = APIRouter(
    prefix="/v1/me",
    tags=["me"],
)


class MyWorkResponse(BaseModel):
    id: str
    title: str
    type: str
    repo_name: str
    status: str
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


@router.get("/work", response_model=list[MyWorkResponse])
def get_my_work(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    task_rows = db.execute(
        select(Task, Repository.name)
        .join(Repository, Task.repository_id == Repository.id)
        .where(
            or_(
                Task.assigned_user_id == current_user.id,
                Task.created_by == current_user.id,
                Repository.owner_id == current_user.id,
            )
        )
        .order_by(Task.updated_at.desc())
        .limit(50)
    ).all()

    results = []
    for task, repo_name in task_rows:
        results.append(
            MyWorkResponse(
                id=task.id,
                title=task.title,
                type="task",
                repo_name=repo_name,
                status=task.status,
                updated_at=task.updated_at,
            )
        )

    return results


class StatsResponse(BaseModel):
    ci_pass_rate: float | None
    ci_jobs_total: int
    agent_changes: int
    human_changes: int
    median_lead_time_minutes: int | None
    security_findings: int


@router.get("/stats", response_model=StatsResponse)
def get_my_stats(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return real workspace statistics instead of demo values."""
    return _build_stats(current_user, db)


class ActivityResponse(BaseModel):
    id: str
    actor_name: str
    action: str
    target: str
    repo_name: str
    created_at: datetime


@router.get("/activity", response_model=list[ActivityResponse])
def get_my_activity(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Return recent activity generated by the user's workspace."""
    return _build_activity(current_user, db)


class DashboardCIResponse(BaseModel):
    jobs_total: int
    passed: int
    failed: int
    running: int
    pass_rate: float | None


class DashboardDeploymentsResponse(BaseModel):
    total: int
    successful: int
    failed: int
    running: int
    last_status: str | None
    last_created_at: datetime | None


class DashboardAgentResponse(BaseModel):
    total: int
    active_sessions: int


class DashboardSecurityResponse(BaseModel):
    open_findings: int
    critical: int
    high: int
    medium: int
    low: int


class DashboardActivityResponse(BaseModel):
    id: str
    actor_name: str
    action: str
    target: str
    repo_name: str
    created_at: datetime


class DashboardResponse(BaseModel):
    repository_count: int
    open_changes: int
    changes_needing_review: int
    agent_changes: int
    human_changes: int
    median_lead_time_minutes: int | None
    active_agent_sessions: int
    ci: DashboardCIResponse
    security: DashboardSecurityResponse
    deployments: DashboardDeploymentsResponse
    activity: list[DashboardActivityResponse]


@router.get("/dashboard", response_model=DashboardResponse)
def get_dashboard(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Aggregate authoritative workspace data for the Home dashboard."""
    repo_ids = _owned_repository_ids(current_user, db)
    stats = _build_stats(current_user, db, repo_ids=repo_ids)
    activity = _build_activity(current_user, db, repo_ids=repo_ids)

    open_changes = 0
    changes_needing_review = 0
    agent_changes = 0
    human_changes = 0

    if repo_ids:
        change_rows = db.execute(
            select(Change, Actor)
            .join(Actor, Actor.id == Change.actor_id)
            .where(Change.repository_id.in_(repo_ids))
        ).all()

        for change, actor in change_rows:
            if change.status in {"proposed", "recorded", "blocked"}:
                open_changes += 1
            if change.status == "proposed":
                changes_needing_review += 1
            if actor.type == "agent":
                agent_changes += 1
            elif actor.type == "human":
                human_changes += 1

    active_agent_sessions = 0
    total_agents = db.scalar(
        select(func.count(Agent.id)).where(
            Agent.owner_id == current_user.id,
        )
    ) or 0

    now = datetime.now(timezone.utc)
    active_agent_sessions = db.scalar(
        select(func.count(AgentSession.id))
        .join(Agent, Agent.id == AgentSession.agent_id)
        .where(
            Agent.owner_id == current_user.id,
            AgentSession.status == "active",
            AgentSession.revoked_at.is_(None),
            AgentSession.expires_at > now,
        )
    ) or 0

    security = _build_security(current_user, db, repo_ids)
    ci = _build_ci(db, repo_ids)
    deployments = _build_deployments(db, repo_ids)
    dashboard_activity = [
        DashboardActivityResponse.model_validate(
            item.model_dump()
        )
        for item in activity
    ]

    return DashboardResponse(
        repository_count=len(repo_ids),
        open_changes=open_changes,
        changes_needing_review=changes_needing_review,
        agent_changes=agent_changes,
        human_changes=human_changes,
        median_lead_time_minutes=stats.median_lead_time_minutes,
        active_agent_sessions=active_agent_sessions,
        ci=ci,
        security=security,
        deployments=deployments,
        activity=dashboard_activity,
)


def _owned_repository_ids(
    current_user: User,
    db: Session,
) -> list[str]:
    rows = db.scalars(
        select(Repository.id)
        .join(Actor, Actor.id == Repository.owner_id)
        .where(
            Actor.owner_id == current_user.id,
            Repository.deleted_at.is_(None),
        )
    ).all()
    return list(rows)


def _build_ci(
    db: Session,
    repo_ids: list[str],
) -> DashboardCIResponse:
    if not repo_ids:
        return DashboardCIResponse(
            jobs_total=0,
            passed=0,
            failed=0,
            running=0,
            pass_rate=None,
        )

    jobs = db.scalars(
        select(CIJob).where(
            CIJob.repository_id.in_(repo_ids),
        )
    ).all()

    passed = sum(
        1 for job in jobs
        if job.status == CIJob.STATUS_PASSED
    )
    failed = sum(
        1 for job in jobs
        if job.status in {
            CIJob.STATUS_FAILED,
            CIJob.STATUS_TIMED_OUT,
        }
    )
    running = sum(
        1 for job in jobs
        if job.status in {
            CIJob.STATUS_QUEUED,
            CIJob.STATUS_RUNNING,
        }
    )

    completed = passed + failed
    pass_rate = (
        round((passed / completed) * 100, 1)
        if completed
        else None
    )

    return DashboardCIResponse(
        jobs_total=len(jobs),
        passed=passed,
        failed=failed,
        running=running,
        pass_rate=pass_rate,
    )


def _build_security(
    current_user: User,
    db: Session,
    repo_ids: list[str],
) -> DashboardSecurityResponse:
    """
    Use real agent-review security findings already stored by SUTRA.

    This intentionally does not use the old mocked security endpoint.
    Only active inline findings tagged with the SECURITY category count.
    """
    if not repo_ids:
        return DashboardSecurityResponse(
            open_findings=0,
            critical=0,
            high=0,
            medium=0,
            low=0,
        )

    comments = db.scalars(
        select(InlineReviewComment).where(
            InlineReviewComment.repository_id.in_(repo_ids),
            InlineReviewComment.status == InlineReviewComment.STATUS_ACTIVE,
            InlineReviewComment.body.like("[SECURITY]%"),
        )
    ).all()

    counts = {
        "critical": 0,
        "high": 0,
        "medium": 0,
        "low": 0,
    }

    for comment in comments:
        body = comment.body or ""
        first = body.upper().split("]", 1)[0].removeprefix("[")
        if first in counts:
            counts[first] += 1

    return DashboardSecurityResponse(
        open_findings=len(comments),
        critical=counts["critical"],
        high=counts["high"],
        medium=counts["medium"],
        low=counts["low"],
    )


def _build_deployments(
    db: Session,
    repo_ids: list[str],
) -> DashboardDeploymentsResponse:
    if not repo_ids:
        return DashboardDeploymentsResponse(
            total=0,
            successful=0,
            failed=0,
            running=0,
            last_status=None,
            last_created_at=None,
        )

    rows = db.execute(
        select(Deployment)
        .join(Environment, Environment.id == Deployment.environment_id)
        .where(Deployment.repository_id.in_(repo_ids))
        .order_by(Deployment.created_at.desc())
    ).scalars().all()

    successful = sum(
        1 for item in rows
        if item.status == Deployment.STATUS_SUCCESS
    )
    failed = sum(
        1 for item in rows
        if item.status in {
            Deployment.STATUS_FAILED,
            Deployment.STATUS_ROLLED_BACK,
        }
    )
    running = sum(
        1 for item in rows
        if item.status in {
            Deployment.STATUS_QUEUED,
            Deployment.STATUS_DEPLOYING,
        }
    )

    latest = rows[0] if rows else None

    return DashboardDeploymentsResponse(
        total=len(rows),
        successful=successful,
        failed=failed,
        running=running,
        last_status=latest.status if latest else None,
        last_created_at=latest.created_at if latest else None,
    )


def _build_stats(
    current_user: User,
    db: Session,
    repo_ids: list[str] | None = None,
) -> StatsResponse:
    if repo_ids is None:
        repo_ids = _owned_repository_ids(current_user, db)

    ci = _build_ci(db, repo_ids)
    security = _build_security(current_user, db, repo_ids)

    agent_changes = 0
    human_changes = 0

    if repo_ids:
        rows = db.execute(
            select(Change, Actor)
            .join(Actor, Actor.id == Change.actor_id)
            .where(Change.repository_id.in_(repo_ids))
        ).all()
        for change, actor in rows:
            if actor.type == "agent":
                agent_changes += 1
            elif actor.type == "human":
                human_changes += 1

    median_lead = _median_lead_time_minutes(db, repo_ids)

    return StatsResponse(
        ci_pass_rate=ci.pass_rate,
        ci_jobs_total=ci.jobs_total,
        agent_changes=agent_changes,
        human_changes=human_changes,
        median_lead_time_minutes=median_lead,
        security_findings=security.open_findings,
    )


def _median_lead_time_minutes(
    db: Session,
    repo_ids: list[str],
) -> int | None:
    if not repo_ids:
        return None

    rows = db.execute(
        select(Change.created_at, PullRequest.merged_at)
        .join(PullRequest, PullRequest.source_change_id == Change.id)
        .where(
            Change.repository_id.in_(repo_ids),
            PullRequest.merged_at.is_not(None),
        )
    ).all()

    durations = []
    for created_at, merged_at in rows:
        if not created_at or not merged_at:
            continue
        minutes = (
            merged_at - created_at
        ).total_seconds() / 60
        if minutes >= 0:
            durations.append(minutes)

    return (
        round(median(durations))
        if durations
        else None
    )


def _build_activity(
    current_user: User,
    db: Session,
    repo_ids: list[str] | None = None,
) -> list[ActivityResponse]:
    if repo_ids is None:
        repo_ids = _owned_repository_ids(current_user, db)

    if not repo_ids:
        return []

    activities: list[ActivityResponse] = []

    change_rows = db.execute(
        select(Change, Actor, Repository.name)
        .join(Actor, Actor.id == Change.actor_id)
        .join(Repository, Repository.id == Change.repository_id)
        .where(Change.repository_id.in_(repo_ids))
        .order_by(Change.created_at.desc())
        .limit(6)
    ).all()

    for change, actor, repo_name in change_rows:
        activities.append(
            ActivityResponse(
                id=f"change-{change.id}",
                actor_name=actor.name,
                action="created change",
                target=change.intent[:80],
                repo_name=repo_name,
                created_at=change.created_at,
            )
        )

    task_rows = db.execute(
        select(Task, User, Repository.name)
        .join(User, User.id == Task.created_by)
        .join(Repository, Repository.id == Task.repository_id)
        .where(Task.repository_id.in_(repo_ids))
        .order_by(Task.created_at.desc())
        .limit(6)
    ).all()

    for task, user, repo_name in task_rows:
        activities.append(
            ActivityResponse(
                id=f"task-{task.id}",
                actor_name=user.username,
                action="created task",
                target=task.title[:80],
                repo_name=repo_name,
                created_at=task.created_at,
            )
        )

    deployment_rows = db.execute(
        select(Deployment, Repository.name)
        .join(Repository, Repository.id == Deployment.repository_id)
        .where(Deployment.repository_id.in_(repo_ids))
        .order_by(Deployment.created_at.desc())
        .limit(6)
    ).all()

    for deployment, repo_name in deployment_rows:
        activities.append(
            ActivityResponse(
                id=f"deployment-{deployment.id}",
                actor_name=deployment.actor_id[:8],
                action=f"deployment {deployment.status}",
                target=deployment.commit_sha[:8],
                repo_name=repo_name,
                created_at=deployment.created_at,
            )
        )

    activities.sort(
        key=lambda item: item.created_at,
        reverse=True,
    )

    return activities[:12]
